### DISCUSSION TITLE
Flashing ESP32 Error: The program size is greater than maximum allowed

### DISCUSSION THREAD

**Discussion by Morcegolas** [SmartHome-yourself/sonoff-tx-ultimate-for-esphome#65] [Q&A]
Hello, after I added this code I got an error when trying to flash it wirelessly, saying the program size is greater than maximum allowed. If I comment this code I can install it. Can anybody help me please?

```
## Enable Bluetooth Proxy
esp32_ble_tracker:
    scan_parameters:
      continuous: false
      active: true
      interval: 320ms # suggested 211ms # default 1100ms
      window:   300ms # suggested 120ms # default 1100ms

bluetooth_proxy:
  active: true
```

This is the final part of the Log:

```
--
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 2.1.4
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.2.2
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- noise-c @ 0.1.6
|-- Improv @ 1.2.4
|-- NeoPixelBus @ 2.7.3
|-- WiFiClientSecure @ 2.0.0
|-- HTTPClient @ 2.0.0
|-- ESP32-audioI2S @ 2.0.7
RAM:   [==        ]  17.5% (used 57228 bytes from 327680 bytes)
Flash: [==========]  112.7% (used 2068073 bytes from 1835008 bytes)
Error: The program size (2068073 bytes) is greater than maximum allowed (1835008 bytes)
*** [checkprogsize] Explicit exit, status 1
========================== [FAILED] Took 9.39 seconds ==========================

```
