### ISSUE TITLE
NeoPixel and nightlight

### ISSUE THREAD

**Issue by tiagombrito** [SmartHome-yourself/sonoff-tx-ultimate-for-esphome#14]
Hello, 

I'm wondering if what i'm observing is the intended behaviour of the wall switch.

When I turn the NeoPixel light on and then push one of the touchfields, the light is turned off.
In home assistant the entity is still shown as on.
I've seen this happening in 3 different devices, with 1 and 2 channels

When i do the same thing with the nightlight, the light doesn't turn off, but it dims and returns to full brightness 2 seconds later.

Thank you.

**Comment by tiagombrito** [comment]
I'm thinking this may happen because of the light effects on touch, multi touch, etc. that are overriding the neopixel light.
I made all effect brightnesses 0 so as to not have any effects, is there any more appropriate way to do have no effects?

**Comment by barth11** [comment]
I have a similar problem. I don't use nightlight but I created an automation which on multitouch enables Pulse effect which I have to repeat after multitouch effect is done...now I have it set to repeat after 3 seconds.
When I don't do it the Neopixel is still on but LEDs are off and only the status LEDs are pulsing 😁
See here: https://streamable.com/22ah2w

This automation with the delay is a workaround this problem because it enables the Pulse after the multitouch effect is done effecting...
Delay could be as the first step but I wanted the LEDs to react immediately so that's why it's like that.
```
alias: Enable/Disable LED TX1
description: ""
trigger:
  - type: turned_off
    platform: device
    device_id: 4630bde13982e46e50fe7b6aff640287
    entity_id: ed83d39e9d3ecaf2ab120894e5cb1724
    domain: binary_sensor
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: light.txultimate2_neopixel_light
            state: "on"
        sequence:
          - service: light.turn_off
            data: {}
            target:
              entity_id: light.txultimate2_neopixel_light
      - conditions:
          - condition: state
            entity_id: light.txultimate2_neopixel_light
            state: "off"
        sequence:
          - service: light.turn_on
            target:
              entity_id: light.txultimate2_neopixel_light
            data:
              rgb_color:
                - 236
                - 55
                - 168
              brightness: 254
              effect: Pulse
          - delay:
              hours: 0
              minutes: 0
              seconds: 3
              milliseconds: 0
          - service: light.turn_on
            target:
              entity_id: light.txultimate2_neopixel_light
            data:
              rgb_color:
                - 236
                - 55
                - 168
              brightness: 255
              effect: Pulse
```

Interestingly this workaround doesn't work for Neopixel effect "None". As far as I tested it for now.
