### ISSUE TITLE
tx_ultimate_cover.yaml - Wrong cover brightness after swipe right

### ISSUE THREAD

**Issue by AtoMediaDesign** [SmartHome-yourself/sonoff-tx-ultimate-for-esphome#36]
I just implemented the TX Ultimate with 2 buttons as cover control in four rooms with customized nightlight and cover brightness. Awesome! :)

But especially in the bed room I noticed, that the pretty dim cover position LEDs I specified light up with nearly full brightness after a swipe from left to right, which I used to control the night light in the bath with a sleep timer.

I studied the script tx_ultimate_cover.yaml a bit and found out that the cover brightness restoriation is missing at the end of script "led_on_swipe_right". I tried it out locally and with this change it works like intended:

```
  - id: led_on_swipe_right
    mode: restart
    then:
      - light.turn_on:
          id: leds_right
          brightness: ${swipe_right_brightness}
          red: !lambda "return id(swipe_right_color)[0]/100.0;"
          green: !lambda "return id(swipe_right_color)[1]/100.0;"
          blue: !lambda "return id(swipe_right_color)[2]/100.0;"
          effect: ${swipe_right_effect}
      - delay: 2.4s
      - light.turn_on:
          id: leds_right
          brightness: ${cover_brightness}  # This is missing!
          effect: "Cover Position"
```

I haven't looked into the other scripts, but maybe it's also missing there as well.
