### ISSUE TITLE
HTTP request control for Ultimate 2 Gang

### ISSUE THREAD

**Issue by Caddyrdn** [SmartHome-yourself/sonoff-tx-ultimate-for-esphome#66]
Is it possible to implement HTTP request control? I would like to enable switching on via the IP address.

But I don't know how to implement it.

**Comment by barth11** [comment]
You can use HA webhook to trigger and automation. Different payloads can trigger different actions so you don't have to split it into many automations.
https://www.home-assistant.io/docs/automation/trigger/#webhook-trigger

**Comment by Caddyrdn** [comment]
Thanks
Can you help me how to use it? ESPhome is completely new to me.

**Comment by barth11** [comment]
Automation example. Replace device_id and entity_id.
```
alias: Webhook example
description: ""
triggers:
  - trigger: webhook
    allowed_methods:
      - POST
      - PUT
    local_only: true
    webhook_id: "<generated_webhook>"
conditions: []
actions:
  - type: toggle
    device_id: <your_device_id>
    entity_id: <your_entity_id>
    domain: switch
mode: single

```


Sending POST request with below URL will trigger the automation. 
```
http://homeassistant.local:8123/api/webhook/<generated_webhook>
```
